### PR TITLE
UI menu

### PR DESCRIPTION
**Pull request by ParthPan7**
@RoseDuf  I have added MFC Support Modules for adding UI Menu to the Project. 
Please, Kindly install MFC C++ dependency from Visual Studio Installer or tag me to help you out to configure it locally.

Note: when you pull latest and have had installed MFC dependencies -- your compilation should be error less thereafter.
Expected Behavior :  you must expect a small Popup Dialog with some message.
Cheers!

### CODE REVIEW

**Comment by RoseDuf** [comment]
we should probably establish a code conduct right?
PascalCase for functions and camelCase for variables?

private variables: "_variableName"
public variables: "variableName"

const variables: "VARIABLE_NAME"

what do you think?

**Comment by ParthPan7** [comment]
> we should probably establish a code conduct right? PascalCase for functions and camelCase for variables?
> 
> private variables: "_variableName" public variables: "variableName"
> 
> const variables: "VARIABLE_NAME"
> 
> what do you think?

That would be a good conduct and standard practice as well.

**Comment by ParthPan7** [comment]
@RoseDuf what should be conventions about class naming ? PascalCase or _PascalCase. I am refactor my code as per then after.

Here is something I would like to suggest 👍 
1. **_camelCase** for function names ( user defined ).
2.  **camelCase** for variables. 
3.  **PascalCase** for class names.

**Comment by RoseDuf** [comment]
> @RoseDuf what should be conventions about class naming ? PascalCase or _PascalCase. I am refactor my code as per then after.
> 
> Here is something I would like to suggest 👍
> 
> 1. **_camelCase** for function names ( user defined ).
> 2. **camelCase** for variables.
> 3. **PascalCase** for class names.

I would rather:

PascalCase for classes
camelCase for functions and public variables
_camelCase for private variables

**Comment by ParthPan7** [comment]
> > @RoseDuf what should be conventions about class naming ? PascalCase or _PascalCase. I am refactor my code as per then after.
> > Here is something I would like to suggest 👍
> > 
> > 1. **_camelCase** for function names ( user defined ).
> > 2. **camelCase** for variables.
> > 3. **PascalCase** for class names.
> 
> I would rather:
> 
> PascalCase for classes camelCase for functions and public variables _camelCase for private variables

Finalize of what has been said by you and refactoring as per. Try to review and merge.

**Pull request merged**
